### ISSUE TITLE
Shoebill 2.0-RC Crash - old dependency ?

### ISSUE THREAD

**Issue by Alf21** [Shoebill/ShoebillPlugin#7]
Can you please compile this Plugin to support the new 2.0-RC version and provide it here?
Currently i'm not able to compile it (on my computer (arch)) and it would be much more easier for everyone.

Thank you :)

----

// edit - old message:

Shoebill-Plugin crashes on every start.
I also tried to get the Shoebill Dependency Manager and the Shoebill Runtime & Launcher from maven host, but everytime i start the server, i was told that i need to update the dependencies (to an older version). Maybe you need to update these dependencies on your host?

BTW: I've updated the Shoebill.dll and Shoebill.so (downloaded from bplaced.net host).

Here is the server.log:

```
loading Shoebill...
-------------------

----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team


Server Plugins
--------------
 Loading plugin: Shoebill
  > Shoebill 1.3 NativePlugin for SA-MP 0.3.7 by MK124, JoJLlmAn & 123marvin123
  > Java VM has been created.
Shoebill Dependency Manager 1.0-SNAPSHOT (for net.gtaun:shoebill-api:1.1)
Build date: 2015-05-04 16:25:57 MESZ (+0200)
Resolving dependencies...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
Ignored artifact me.alf21:base:jar:1.0-SNAPSHOT (Override: shoebill\gamemodes\ba
se-1.0-SNAPSHOT.jar)
Resolved artifact net.gtaun:shoebill-runtime:jar:2.0-RC from local
Resolved artifact net.gtaun:shoebill-utilities:jar:2.0-RC from gtaun-public-repo

Resolved artifact org.yaml:snakeyaml:jar:1.19 from gtaun-public-repo
Resolved artifact org.slf4j:slf4j-log4j12:jar:1.7.25 from gtaun-public-repo
Resolved artifact org.slf4j:slf4j-api:jar:1.7.25 from gtaun-public-repo
Resolved artifact log4j:log4j:jar:1.2.17 from gtaun-public-repo
Resolved artifact org.jetbrains.kotlin:kotlin-stdlib-jre8:jar:1.1.51 from gtaun-
public-repo
Resolved artifact org.jetbrains.kotlin:kotlin-stdlib:jar:1.1.51 from gtaun-publi
c-repo
Resolved artifact org.jetbrains:annotations:jar:13.0 from central
Resolved artifact org.jetbrains.kotlin:kotlin-stdlib-jre7:jar:1.1.51 from gtaun-
public-repo
Resolved artifact com.mindscapehq:core:jar:2.2.0 from central
Resolved artifact com.google.code.gson:gson:jar:2.2.4 from central
Resolved artifact net.gtaun:shoebill-common:jar:2.0-RC from local
Resolved artifact org.jetbrains.kotlin:kotlin-reflect:jar:1.1.51 from gtaun-publ
ic-repo
Resolved artifact net.gtaun:shoebill-api:jar:2.0-RC from gtaun-public-repo
Resolved artifact net.gtaun:util-event:jar:2.0-RC from gtaun-public-repo
Resolved artifact org.apache.commons:commons-lang3:jar:3.6 from gtaun-public-rep
o
Resolved artifact org.reflections:reflections:jar:0.9.11 from gtaun-public-repo
Resolved artifact com.google.guava:guava:jar:20.0 from gtaun-public-repo
Resolved artifact org.javassist:javassist:jar:3.21.0-GA from gtaun-public-repo
java.lang.NullPointerException
        at net.gtaun.shoebill.util.config.AbstractConfiguration.getBoolean(Abstr
actConfiguration.java:181)
        at net.gtaun.shoebill.util.config.AbstractConfiguration.getBoolean(Abstr
actConfiguration.java:173)
        at net.gtaun.shoebill.ShoebillConfig.<init>(ShoebillConfig.java:88)
        at net.gtaun.shoebill.ShoebillImpl.<init>(ShoebillImpl.kt:50)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at net.gtaun.shoebill.ShoebillLauncher.createShoebill(ShoebillLauncher.j
ava:75)
ShoebillPlugin Error: Can't create shoebill object.
  Loaded.
 Loaded 1 plugins.


Started server on port: 7777, with maxplayers: 500 lanmode is OFF.


Filterscripts
---------------
  Loading filterscript 'TDEJava.amx'...

--------------------------------------
 Text Draw Editor 1.0RC2 (v3.1) by Zamaroht for SA-MP 0.3 Loaded.
--------------------------------------

  Loaded 1 filterscripts.


----------------------------------
 Server by Alf21
----------------------------------

Number of vehicle models: 0
```

**Comment by 123marvin123** [comment]
The plugin from the bplaced host is still the 1.3 files. You need to compile 2.0-RC yourself currently or join Slack and I can make it available for testing.
